/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#eeeeee",
        "primary-container": "#1b1b1b",
        "on-primary-fixed": "#1b1b1b",
        "surface-container-high": "#e8e8e8",
        "background": "#F4F4F0",
        "on-tertiary-fixed-variant": "#930013",
        "on-tertiary-fixed": "#410004",
        "on-secondary-fixed-variant": "#464747",
        "primary-fixed-dim": "#c6c6c6",
        "error-container": "#ffdad6",
        "surface-container-low": "#f3f3f4",
        "on-tertiary-container": "#ef4444",
        "tertiary-fixed-dim": "#ffb3ad",
        "tertiary": "#000000",
        "secondary-fixed": "#e3e2e2",
        "surface": "#f9f9f9",
        "secondary-container": "#e3e2e2",
        "tertiary-fixed": "#ffdad7",
        "on-secondary-container": "#646464",
        "surface-tint": "#5e5e5e",
        "secondary-fixed-dim": "#c7c6c6",
        "on-error-container": "#93000a",
        "on-background": "#1a1c1c",
        "inverse-primary": "#c6c6c6",
        "surface-dim": "#dadada",
        "outline-variant": "#cfc4c5",
        "on-primary-fixed-variant": "#474747",
        "outline": "#7e7576",
        "on-primary-container": "#848484",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#4c4546",
        "tertiary-container": "#410004",
        "on-secondary-fixed": "#1b1c1c",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "inverse-surface": "#2f3131",
        "primary-fixed": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f9f9f9",
        "secondary": "#5e5e5e",
        "on-surface": "#1a1c1c",
        "inverse-on-surface": "#f0f1f1",
        "surface-container-highest": "#e2e2e2",
        "primary": "#000000",
        "on-error": "#ffffff",
        "brutal-yellow": "#E2FF32",
        "brutal-red": "#FF4911",
        "brutal-purple": "#B497FF",
        "brutal-cyan": "#00E5FF",
        "brutal-black": "#000000"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "0px"
      },
      spacing: {
        "section-gap": "64px",
        "gutter": "16px",
        "container-margin": "32px",
        "unit": "4px"
      },
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
